/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jasa;

import Koneksi.Db_Koneksi;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author selam
 */
    public class datapemesanan extends javax.swing.JFrame {
    private com.mysql.jdbc.Connection con;
    private com.mysql.jdbc.Statement stat;
    private ResultSet res;
    private String t;
     private DefaultTableModel model;
    String Id_Member, Nama, Alamat, 
     Jenis, Email, Telepon, Lokasi;
    /**
     * Creates new form datapemesanan;
     */
    public datapemesanan() {
        initComponents();
        koneksi();
        tabel1();
        
        
    }
    
    private void loadData() {
        Id_Member  = txtId_Member.getText();
        Nama	   = txtNama.getText();
        Alamat  =  txtAlamat.getText();
        Jenis = (String) cmboxJenis.getSelectedItem();
        Email   = txtEmail.getText();
        Telepon = txtTelepon.getText();
        Lokasi = txtLokasi.getText();
    }
    
    private void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
            con=(com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_pesanan", "root", "");
            stat=(com.mysql.jdbc.Statement) con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }
    
    private void tabel1(){ 
    DefaultTableModel t= new DefaultTableModel();
    t.addColumn("Id_Member"); 
    t.addColumn("Nama");
    t.addColumn("Alamat");
    t.addColumn("Jenis Kelamin");
    t.addColumn("Email");
    t.addColumn("No Telpon");
    t.addColumn("Lokasi Acara");

    tbl_Pesanan.setModel(t); try{ res=stat.executeQuery("select * from tbl_Pesanan"); 
    while (res.next()) { 
    t.addRow(new Object[]{ 
    res.getString("Id_Member"),
    res.getString("Nama"), 
    res.getString("Alamat"), 
    res.getString("Jenis_Kelamin"), 
    res.getString("Email"), 
    res.getString("No_Telp"), 
    res.getString("Lokasi_Acara"), 
    }); 
    }
    }catch (Exception e) { 
    ; 
    }
    }
    
    private void riset(){
    txtId_Member.setText("");
    txtNama.setText("");
    txtAlamat.setText("");
    txtEmail.setText("");
    txtTelepon.setText("");
    txtLokasi.setText("");
    
    }
    
    
     private void updateData() {
  koneksi();
  loadData();
try{
	Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
	String sql = "Update tbl_pesanan Set Nama 	= '"+ Nama +"',"
				+ "Alamat	        = '"+ Alamat +"',"
				+ "Jenis_kelamin 	= '"+ Jenis +"',"
                                + "Email 	        = '"+ Email +"',"
                                + "No_Telp 	        = '"+ Telepon +"',"
				+ "Lokasi_Acara 	= '"+ Lokasi+"' Where Id_Member = '"+ Id_Member +"'";
        PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);	
	p.executeUpdate();
	riset();
	JOptionPane.showMessageDialog(null, "Update Berhasil...");
        tabel1();
	}catch(SQLException err){
		JOptionPane.showMessageDialog(null, err.getMessage());
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtId_Member = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtLokasi = new javax.swing.JTextField();
        cmboxJenis = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Pesanan = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        javax.swing.JButton btnKeluar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id Member");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 40, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Telepon");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 240, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lokasi Acara");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 280, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 80, 150, 30);

        txtId_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_MemberActionPerformed(evt);
            }
        });
        getContentPane().add(txtId_Member);
        txtId_Member.setBounds(120, 40, 110, 30);
        getContentPane().add(txtNama);
        txtNama.setBounds(120, 80, 180, 30);
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(120, 120, 180, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(120, 200, 180, 30);
        getContentPane().add(txtTelepon);
        txtTelepon.setBounds(120, 240, 180, 30);
        getContentPane().add(txtLokasi);
        txtLokasi.setBounds(120, 280, 180, 30);

        cmboxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki_Laki", "Perempuan" }));
        getContentPane().add(cmboxJenis);
        cmboxJenis.setBounds(120, 160, 180, 30);

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_Pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Pesanan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 40, 610, 460);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(20, 330, 130, 50);

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Close.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(160, 450, 140, 51);

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Undo.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(160, 330, 140, 51);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(20, 390, 280, 51);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(20, 450, 130, 51);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Isi Data Pemesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 930, 30);

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari);
        cari.setBounds(240, 40, 60, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 934, 520);

        setSize(new java.awt.Dimension(954, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtId_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_MemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_MemberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        koneksi();
        try {
        stat.executeUpdate("insert into tbl_Pesanan values (" 
       
        + "'" + txtId_Member.getText()+"',"        
        + "'" + txtNama.getText()+"',"
        + "'" + txtAlamat.getText()+"',"
        + "'" + cmboxJenis.getSelectedItem()+"',"
        + "'" + txtEmail.getText()+ "',"
        + "'" + txtTelepon.getText()+"',"
        + "'" + txtLokasi.getText()+"')");
        riset();
        JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data"); 
        } catch (SQLException | HeadlessException e) { 
        JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }finally{
        tabel1();
        }             
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        riset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        koneksi();
        loadData();
	int pesan = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus Data"+ Id_Member +"?","Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
	if (pesan == JOptionPane.OK_OPTION){
	try{
	Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
	String sql = "DELETE FROM tbl_pesanan WHERE Id_Member = '"+ Id_Member +"'";
	PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);	
	p.executeUpdate();
	tabel1();
	riset();
	JOptionPane.showMessageDialog(null, "Delete Berhasil");
	}catch(SQLException err){
		JOptionPane.showMessageDialog(null, err.getMessage());
	}
       } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbl_PesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PesananMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_tbl_PesananMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        try {
            res=stat.executeQuery("select * from tbl_Pesanan where "+ "Id_Member='" +txtId_Member.getText()
                +"'" );
            while (res.next())
            {
                txtId_Member.setText(res.getString("Id_Member"));
                txtNama.setText(res.getString("Nama"));
                txtAlamat.setText(res.getString("Alamat"));
                cmboxJenis.setSelectedItem(res.getString("Jenis_Kelamin"));
                txtEmail.setText(res.getString("Email"));
                txtTelepon.setText(res.getString("No_Telp"));
                txtLokasi.setText(res.getString("Lokasi_Acara"));
                  
                
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_cariActionPerformed
 private void dataSelect() {
    int i = tbl_Pesanan.getSelectedRow();
	if (i ==-1){
	return;
}
txtId_Member.setText(""+model.getValueAt(i, 0));
txtNama.setText(""+model.getValueAt(i, 1));
txtAlamat.setText(""+model.getValueAt(i, 2));
cmboxJenis.setSelectedItem(""+model.getValueAt(i, 3));
txtEmail.setText(""+model.getValueAt(i, 4));
txtTelepon.setText(""+model.getValueAt(i, 5));
txtLokasi.setText(""+model.getValueAt(i, 6));    
 }
 
    
 
 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapemesanan().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cmboxJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Pesanan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId_Member;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables

   
   
}
